name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build -x test
    
    - name: Build Docker image
      run: docker build -t cnq:${{ github.sha }} .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Tag and Push to Docker Hub
      run: |
        docker tag cnq:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/cnq:latest
        docker tag cnq:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/cnq:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/cnq:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/cnq:${{ github.sha }}
